### ISSUE TITLE
Whether it can be marked differently from getx in the document

### ISSUE THREAD

**Issue by laterdayi** [Aniketkhote/refreshed#1]
Whether it can be marked differently from getx in the document

This includes addressing specific getx issues

**Comment by aniketkhote9** [comment]
Yes, indeed. In the documentation, we'll make sure to mark the differences from the original GetX library prominently. This will help users distinguish between the two and understand the unique features and improvements offered by this package. Additionally, we'll ensure to address specific GetX issues as part of our ongoing efforts to enhance compatibility and reliability.

Thank you for bringing this up, and we appreciate your attention to detail!
