### ISSUE TITLE
I am trying to use this package v-2.4.1, but there is an error

### ISSUE THREAD

**Issue by WFCN** [Aniketkhote/refreshed#10]
The error is as follows：

Because every version of flutter_test from sdk depends on web 0.3.0 and refreshed   
  >=2.3.1 depends on web >=0.4.0 <0.6.0, flutter_test from sdk is incompatible with 
  refreshed >=2.3.1.
So, because flutter_application_7 depends on both refreshed ^2.4.1 and
  flutter_test from sdk, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on refreshed: flutter pub add refreshed:^1.5.4

----------------------------------------------------------
The version I am using is as follows：

Flutter 3.16.9 • channel stable • https://github.com/flutter/flutter.git 
Framework • revision 41456452f2 (8 weeks ago) • 2024-01-25 10:06:23 -0800
Engine • revision f40e976bed
Tools • Dart 3.2.6 • DevTools 2.28.5

--------------------------------------------------------------
Should I update to the latest version before using this package？

**Comment by Aniketkhote** [comment]
Could you please share the pubspec.yaml file?

**Comment by WFCN** [comment]
> Could you please share the pubspec.yaml file?

[pubspec.zip](https://github.com/Aniketkhote/refreshed/files/14648436/pubspec.zip)

**Comment by Aniketkhote** [comment]
Could you please update the package to the latest version?

**Comment by WFCN** [comment]
I am currently unable to upgrade to the latest version of Flutter. Once Flutter 3.19. x is stable, I will try refreshed this package again，Thanks！
