### ISSUE TITLE
kindly support old getx projects don't depreciate each thing, make it work also need some help with bindings stuff

### ISSUE THREAD

**Issue by fisforfaheem** [Aniketkhote/refreshed#12]
i ma doing like this:    

//aboutUsScreen,
    GetPage(
      name: aboutUsScreen,
      page: () => const AboutUsScreen(),
    ),
    // SeeAllReviewPage,
    GetPage(
      name: seeAllReviewPage,
      page: () => SeeAllReviewPage(),
      bindings: [
        SeeAllReviewBinding(),
      ],
    ),
  is this correct way

**Comment by Aniketkhote** [comment]
I noticed that you're using the bindings parameter in your code. Instead of specifying **bindings** as a list, you should use **binding** as a singular parameter. So, your code should look like this:

**binding: SeeAllReviewBinding()**
