### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by FluffyDiscord** [Aniketkhote/refreshed#13]
**Is your feature request related to a problem? Please describe.**
There is no real documentation one can follow to see what are the suggested/best approaches to things - routing, DI, widgets, etc.

**Describe the solution you'd like**
Simple documentstion briefly explaining individual parts.

**Describe alternatives you've considered**
API reference cannot be considered as documentation.

**Comment by Aniketkhote** [comment]
Thank you for your feedback! I'm actively working on documentation, but it will take some time to publish. In the meantime, you can check out resources like https://chornthorn.github.io/getx-docs/ for helpful guidance.

**Comment by victorlunam** [comment]
@Aniketkhote 

I would like to help in the development of the documentation, I have some questions.

1. Is there a roadmap for the documentation?
2. Will the documentation be done in a different repository ?
3. Do you plan to use flutter web ? or are you open to use web frameworks like nextjs, remix, nuxt ... among others

**Comment by fisforfaheem** [comment]
@Aniketkhote kindly let @victorlunam help out.

**Comment by Aniketkhote** [comment]
Thank you for your interest in contributing to the documentation! Currently, we don’t have a specific roadmap or plans for the documentation, as we are occupied with other projects at the moment. However, you’re more than welcome to help improve the documentation by taking inspiration and references from the GetX package. Your contributions would be greatly appreciated!

**Comment by fisforfaheem** [comment]
@Aniketkhote dear why have u stopepd workign on the package??? also why arent u not ocntributing anymore?

**Comment by Aniketkhote** [comment]
Hey, I haven't stopped contributing! The past few weeks have been busy with other projects, so I haven't been able to dedicate as much time to the package. But I’m planning to get back to it soon. Thanks for your patience!
