### ISSUE TITLE
Provide getx5 > refresh migration guide

### ISSUE THREAD

**Issue by laterdayi** [Aniketkhote/refreshed#14]
Provide getx5 > refresh migration guide

**Comment by Aniketkhote** [comment]
GetX 5 and Refreshed are essentially the same; we just removed some unrelated functionality. DI, Navigation, and State Management remain unchanged.

**Comment by Macacoazul01** [comment]
@Aniketkhote Where are the docs from the getx v4 > refreshed migration?
