### ISSUE TITLE
how to fix this?

### ISSUE THREAD

**Issue by fisforfaheem** [Aniketkhote/refreshed#15]
<img width="513" alt="Screenshot 2024-04-08 at 9 06 51 PM" src="https://github.com/Aniketkhote/refreshed/assets/35878088/30e17836-e112-4955-a48a-ae738ae06d8d">

this initial bindings...

<img width="716" alt="Screenshot 2024-04-08 at 9 07 39 PM" src="https://github.com/Aniketkhote/refreshed/assets/35878088/b440cc72-1b8e-455b-b6ac-7535bacac98c">

**Comment by nandakista** [comment]
what's the problem and what do you expect?

**Comment by fisforfaheem** [comment]
dont break bindings

**Comment by nandakista** [comment]
Please look at the documentation first
Based on getx5 documentation, the binding should look like this

<img width="686" alt="Screenshot 2024-04-29 at 05 57 37" src="https://github.com/Aniketkhote/refreshed/assets/47182823/26d826ae-8ec6-474a-8aa0-525cccc958b6">

**Comment by fisforfaheem** [comment]
but i am using like this : 
![image](https://github.com/Aniketkhote/refreshed/assets/35878088/02f891e0-0121-4f39-8dcb-17c97fa5baa7)

**Comment by nandakista** [comment]
Ah thats the problem, you missing close bracket twice
line 13 should look like this
```Bind.lazyPut(() => DisputeScreenController(DisputeScreenModel()))```

**Comment by Aniketkhote** [comment]
@fisforfaheem If your issue is resolved, kindly close it

**Comment by fisforfaheem** [comment]
Help
