### ISSUE TITLE
wont let me use anything :( please help and fix

### ISSUE THREAD

**Issue by fisforfaheem** [Aniketkhote/refreshed#17]
![image](https://github.com/Aniketkhote/refreshed/assets/35878088/a94a026c-6c88-47b8-9bf9-6f7c730ec896)

**Comment by nandakista** [comment]
Based on getx5 documentation, the binding should look like this

<img width="686" alt="Screenshot 2024-04-29 at 05 57 37" src="https://github.com/Aniketkhote/refreshed/assets/47182823/ac38be8e-d281-42e8-bfaf-4ddfc593c42a">

*please look at the documentation first

**Comment by Aniketkhote** [comment]
@fisforfaheem If your issue is resolved, kindly close it

**Comment by fisforfaheem** [comment]
Not resolved
