### ISSUE TITLE
binding error 2

### ISSUE THREAD

**Issue by fisforfaheem** [Aniketkhote/refreshed#18]
![image](https://github.com/Aniketkhote/refreshed/assets/35878088/5b2c1226-5cc2-4f51-a656-e2cf6d015a82)

but even after fixing: 
![image](https://github.com/Aniketkhote/refreshed/assets/35878088/43b0f841-c428-4a56-af28-55c58b4782b0)
****  my isuse not reprieved why??

**Comment by fisforfaheem** [comment]
![image](https://github.com/Aniketkhote/refreshed/assets/35878088/02b68075-37f7-4cc8-abea-8f97e963c5b9)

**Comment by nandakista** [comment]
Please see getx5 documentation
Update your binding like this.

<img width="686" alt="image" src="https://github.com/Aniketkhote/refreshed/assets/47182823/928581c9-84be-458e-9414-02aae96b80bf">

**Comment by nandakista** [comment]
the binding and getPage seems ok, but the following error looks like failed import the refreshed package
can you please restart your IDE or **flutter clean** and re-get pub dependencies using **flutter pub get** ?

**Comment by Aniketkhote** [comment]
Could you please share a minimal sample of code for testing?

**Comment by asterd** [comment]
There were problems with binding.. it doesn't bind correctly.. what's happen?

**Comment by asterd** [comment]
@Aniketkhote in addition: the latest version that works good with binding is 2.5.2. From 2.5.3 something is broken and some binding were not called correctly and the system throws the Exception "you must call Get.put...."

**Comment by aniketkhote9** [comment]
The interim solution is as follows:

Replace the usage of Bind.lazyPut(() => CountController()) with Bind.lazyPut<CountController>(() => CountController()).

**Comment by asterd** [comment]
@Aniketkhote sorry.. but i didn't see the difference in your example..

**Comment by fisforfaheem** [comment]
Can you kindly come on anydesk for just 5 mins and help me out, I am trying so hard but no luck :(

I dont want to use GETX i want o use refreshed but unable to :

**Comment by Aniketkhote** [comment]
@fisforfaheem If your issue is resolved, kindly close it

**Comment by fisforfaheem** [comment]
Not fixed

**Comment by Aniketkhote** [comment]
@fisforfaheem Check below example, maybe it help to resolve the issue.
https://github.com/Aniketkhote/refreshed/tree/main/demo
https://github.com/Aniketkhote/refreshed/tree/main/demo2

**Comment by asterd** [comment]
@Aniketkhote just a question.
I use a lot the Bind.put<LoginController>(LoginController(), permanent: true) as a porting of the old permanent binding of GetX.

Now, I see in the code that the put method has:

```
static Bind<S> put<S>(
    S dependency, {
    String? tag,
    bool permanent = false,
  }) {
    Get.put<S>(dependency, tag: tag, permanent: permanent);
    return _FactoryBind<S>(
      autoRemove: permanent,
      assignId: true,
      tag: tag,
    );
  }
```

But, autoRemove: permanent means that if I set permanent to true, it autoremoves the controller. In fact, I have this issue since I migrate to your solution: the permanent controllers are disposed automatically..

**Comment by fisforfaheem** [comment]
@Aniketkhote  Brother can i share my repo with you, i cant share it as public, need your help with it, i cant seem to understand even with example u shared.

**Comment by arupbkp** [comment]
use BindingsInterface
