### ISSUE TITLE
one route to another route navigate problem

### ISSUE THREAD

**Issue by arupbkp** [Aniketkhote/refreshed#19]
[Refreshed] GetDelegate is created !
[Refreshed] GetInformationParser is created !
[Refreshed] GetInformationParser: route location: /
[Refreshed] GOING TO ROUTE /

**Comment by Aniketkhote** [comment]
Could you please share a minimal sample of code for testing?

**Comment by arupbkp** [comment]
please share binding example .... getx 5 version wise migrate my project but one route to another route problem..

**Comment by Aniketkhote** [comment]
https://github.com/Aniketkhote/refreshed/tree/main/demo/lib
