### ISSUE TITLE
The getter 'popGestureInProgress' isn't defined for the class 'GetPageRoute<T>'.

### ISSUE THREAD

**Issue by Kuhlemann** [Aniketkhote/refreshed#24]
**Describe the bug**
Flutter Projekt can't be compiled with Refreshed 2.6.3 (2.6.2 does work).

```
../../.pub-cache/hosted/pub.dev/refreshed-2.6.3/lib/get_navigation/src/routes/get_transition_mixin.dart:414:41: Error: The getter 'popGestureInProgress' isn't defined for the class 'GetPageRoute<T>'.
 - 'GetPageRoute' is from 'package:refreshed/get_navigation/src/routes/default_route.dart' ('../../.pub-cache/hosted/pub.dev/refreshed-2.6.3/lib/get_navigation/src/routes/default_route.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'popGestureInProgress'.
    final bool linearTransition = route.popGestureInProgress;
                                        ^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception
```

**Reproduction code**
dependencies:
refreshed: 2.6.3

The code problem seems so be within the refreshed-package.

**To Reproduce**

1. Compile main.dart in DEBUG

flutter clean did not help

**Expected behavior**
A running application as with 2.6.2

**Version:**
Flutter: 3.19.6
Android: 34.0.0
Android Studio: 2023.3

**Refreshed Version:**
2.6.3

**Describe on which device you found the bug:**
Same problem on all devices (physical, virtual)

**Comment by aniketkhote9** [comment]
flutter < 3.19.6 use refreshed 2.6.2
flutter 3.220 use refreshed 2.6.3

**Comment by Kuhlemann** [comment]
Updating to Flutter 3.22.0 with refreshed 2.6.3 did work.
Thanks for the fast reply. :-)
