### ISSUE TITLE
Futurize with statemixin does not run properly in the onEmpty state

### ISSUE THREAD

**Issue by nugrahazzz** [Aniketkhote/refreshed#27]
**Describe the bug**
I used statemixin and futurize but to trigger onEmpty it doesn't work properly. For Widgets that appear in a successful position, onLoading and onError are running properly but onEmpty is not running properly even with the help of change(GetStatus.empty)... Under what conditions is onEmpty triggered? Let's say I have a List of Model, does onEmpty refer to the length of lists = 0 (.isEmpty)?

Futurize (default) method from **rx_notifier.dart**

`  Future<void> futurize(
    Future<T> Function() body, {
    T? initialData,
    String? errorMessage,
    bool useEmpty = true,
  }) async {
    final Future<T> Function() compute = body;
    _value ??= initialData;
    await compute().then(
      (T newValue) {
        if ((newValue == null || newValue._isEmpty()) && useEmpty) {
          status = GetStatus<T>.loading();
        } else {
          status = GetStatus<T>.success(newValue);
        }
        refresh();
      },
      onError: (Object err) {
        status = GetStatus<T>.error(errorMessage ?? err.toString());
        refresh();
      },
    );
  }`

**Change to** 

`Future<void> futurize(
    Future<T> Function() body, {
    T? initialData,
    String? errorMessage,
  }) async {
    final Future<T> Function() compute = body;
    _value ??= initialData;
    await compute().then(
      (T newValue) {
        if (newValue == null) {
          status = GetStatus<T>.loading();
        } else {
          if( newValue!._isEmpty()){
            status = GetStatus<T>.empty();
          } else {
            status = GetStatus<T>.success(newValue);
          }
        }
        refresh();
      },
      onError: (Object err) {
        status = GetStatus<T>.error(errorMessage ?? err.toString());
        refresh();
      },
    );
  }`

**To Reproduce**
I just followed the futurize tutorial on the youtube channel and realized that onEmpty will not be triggered under any circumstances.
https://www.youtube.com/watch?v=5XQkeWy_5Ko

I referenced from the getx issue https://github.com/jonataslaw/getx/issues/2966

**Expected behavior**
onEmpty will be triggered when the data is retrieved and the data is empty

**Screenshots**

**Flutter Version:**
3.22.0

**Refreshed Version:**
2.7.0

**Describe on which device you found the bug:**
IQOO Neo8 Pro, Realme XT, and OPPO F11

**Comment by nugrahazzz** [comment]
![bandicam 2024-07-25 02-57-32-697](https://github.com/user-attachments/assets/bf7f6839-9f21-4d1b-b58f-9d5c152140a8)

hi sir, please fix the futurize method as onEmpty will not be triggered in any condition.

**Comment by nugrahazzz** [comment]
![bandicam 2024-07-25 03-05-58-076](https://github.com/user-attachments/assets/51af09f7-bf4c-4786-95af-672df2e0ec00)

this code will fix the problem

**Comment by Aniketkhote** [comment]
Issue resolved in `v2.8.1`. Please verify if the fix works as expected.

**Comment by nugrahazzz** [comment]
I've done the test and the code works as it should, thanks sir
