### ISSUE TITLE
Should it be fixed and improved based on getx5

### ISSUE THREAD

**Issue by laterdayi** [Aniketkhote/refreshed#3]
Should it be fixed and improved based on getx5

**Comment by Aniketkhote** [comment]
Yes, we've made significant updates and improvements. We forked from the master branch, ensuring that our version is up-to-date with the original GetX repository. This means that you can expect to see enhanced features, improved performance, and possibly new functionalities in the latest version.

From now on, our version may take a different direction. However, as of now, we haven't added any new functionality. Instead, we'll focus on fixing existing package issues that are compatible with the latest Dart and Flutter versions.

**Comment by Aniketkhote** [comment]
I completely understand the anticipation for GetX 5 and the expectations surrounding it to address the limitations of GetX 4, especially regarding context and other functionalities.

While we're all eagerly waiting for updates on GetX 5, we haven't received any news yet. However, I want to let you know that this package is based on the latest master branch of GetX, ensuring that we're aligned with the most recent developments and improvements.

As a part of this process, I've decoupled certain modules that were deemed irrelevant or causing complications. For instance, I've removed GetConnect and published it separately as Connectify. Additionally, I've eliminated animations and widget extensions from the package. 

If you're interested, you can give it a quick try or explore the `quickly` or `do_animate` feature in the meantime.

Looking forward to any feedback or suggestions you might have!

**Comment by laterdayi** [comment]
Yes, a lot of people are looking forward to get5 and how you can help them implement and extend it

**Comment by Aniketkhote** [comment]
Check #5
