### ISSUE TITLE
get_utils should be keep alive

### ISSUE THREAD

**Issue by phatkv** [Aniketkhote/refreshed#36]
Some useful expression like: isLengthLessThan, isLengthGreaterThan, isEmail, isPhone, etc loss in current version. I think it should be keep alive and update soon! Thank you!

**Comment by victorlunam** [comment]
> Some useful expression like: isLengthLessThan, isLengthGreaterThan, isEmail, isPhone, etc loss in current version. I think it should be keep alive and update soon! Thank you!

These helpers were removed from the package with a view to replacing it with an additional [package (Quickly)](https://pub.dev/packages/quickly) that handles all of this in a better way.

https://github.com/Aniketkhote/refreshed/blob/1d038a52b8197199b809ed3c4527947079ed8bca/CHANGELOG.md?plain=1#L100-L103

some examples of replacements could be

```
isLengthLessThan -> minLen
isEmail -> isEmail
isPhone -> unimplemented
```

@Aniketkhote it might be good to implement the most used helpers to facilitate the migration to refreshed

**Comment by aniketkhote9** [comment]
Updated to the latest version with additional string extensions. Let me know if there's anything specific you'd like to see added!
