### ISSUE TITLE
Separating the get_connect Module from GetX

### ISSUE THREAD

**Issue by LianYangCn** [Aniketkhote/refreshed#4]
Hi, Buddy, 

I wonder if it's possible to decouple get_connect just like get_storage.
This would make the entire library more lightweight, and give developers more options.

**Comment by Aniketkhote** [comment]
Absolutely, decoupling `get_connect` similar to `get_storage` would indeed make the library more lightweight and flexible. With many developers opting for services like Firebase or Supabase, not everyone needs an integrated HTTP client. Offering it as a separate installable component would provide developers with more choices based on their project requirements.

**Comment by Aniketkhote** [comment]
> Absolutely, decoupling `get_connect` similar to `get_storage` would indeed make the library more lightweight and flexible. With many developers opting for services like Firebase or Supabase, not everyone needs an integrated HTTP client. Offering it as a separate installable component would provide developers with more choices based on their project requirements.


We're excited to introduce Refreshed_Connect, a streamlined and decoupled alternative to Get_Connect. In response to your feedback and to provide you with more flexibility and choice, we've separated the module from our existing library, creating a standalone solution that's more lightweight and versatile.
