### ISSUE TITLE
decouple state management

### ISSUE THREAD

**Issue by sdegenaar** [Aniketkhote/refreshed#41]
Is there any thought on decoupling the state management so we can just use the state management feature and just use specifically for that? Thanks :-)

**Comment by sdegenaar** [comment]
Has anyone tried pulling it out and using on its own?

**Comment by Gaurav-CareMonitor** [comment]
@Aniketkhote ?

**Comment by Aniketkhote** [comment]
There are no plans to decouple state management, as the package's core pillars are tightly integrated. However, you can still use only the state management feature if that's all you need.
