### ISSUE TITLE
android build fail 

### ISSUE THREAD

**Issue by heshesh2010** [Aniketkhote/refreshed#43]
Hi , i got this error in latest update while try to build android app .

also I want to ask u removed BackLegacy so what is the alternatives back 

./../../.pub-cache/hosted/pub.dev/refreshed-2.10.0/lib/get_navigation/src/navigation_extension.dart:446:57: Error: The method 'withValues' isn't defined for the class 'MaterialColor'.
 - 'MaterialColor' is from 'package:flutter/src/material/colors.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/material/colors.dart').
Try correcting the name to the name of an existing method, or defining a method named 'withValues'.
        backgroundColor: backgroundColor ?? Colors.grey.withValues(alpha: 0.2),
                                                        ^^^^^^^^^^
Target kernel_snapshot_program failed: Exception
2

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/heshamelnemr/Downloads/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Error: Gradle task assembleDebug failed with exit code 1

Exited (1).

**Comment by Aniketkhote** [comment]
Hi,

For the BackLegacy, you can use close for overlays and back for pages as alternatives.

Also, please let me know your Flutter version and provide a code snippet for testing. This will help identify the exact cause of the error and provide a more accurate solution.

**Comment by Aniketkhote** [comment]
Could you please upgrade Flutter to version 3.27

**Comment by Aniketkhote** [comment]
Downgrade to the previous version, as the new version only includes compatibility fixes for 3.27.
